/* file 4 puts
 
 
 * this file is generated by careen naitore
 *
 *
 *
 *
 */
/* header */

#include <stdio.h>

/*
 * includes the work script for putting word
 **/

int main (void)
{ 

	puts("Programming is like building a multilingual puzzle");

		return 0;
}
