/*
 * file 5 
 *
 * generated by careen naitore
 *
 *
 *
 *
 *
 */

/*header */

#include <stdio.h>


/*
 *
 *
 *
 *
 * generate files that prints words
 *
 *
 *
 *
*/


 int main(void)
 {
 	printf("with proper grammar, but the outcome is a piece of art,\n");

		return (0);
		}
